refactor code without ajax
hieulq/pgscm pull request #19
Opened 2017-08-10 18:30 UTC by HaManhDong

2017-08-10 18:33 UTC, HaManhDong commented
It also have a pep8 error at models.Group._deleted_at == None. The pep8 required replace == instead of 'is', but when i replaced it, the results query database were wrong. So i wasn't change it.

2017-08-11 00:57 UTC, hieulq requested changes
@HaManhDong append E711 error code to this line https://github.com/hieulq/pgscm/blob/master/tox.ini#L51

2017-08-11 01:51 UTC, HaManhDong commented
Yes, i have added ignore E711 for flake8

2017-08-11 02:48 UTC, hieulq approved these changes

2017-08-11 02:48 UTC, merged